Fix: 三星浏览器不支持iframe跳转URL Scheme
jawidx/web-launch-app pull request #36
Opened 2021-02-20 06:13 UTC by hanpanpan200

**Main changes:**
- 主流的三星浏览器，使用 `locationCall` 的方式打开（华为P30测试通过）
- 将callend回调中callback中的返回值参数从1，2，3改为了一个常量，方便外部调用
- 将 `landPage` 重命名为 `landingPage`
- 将 `src/index.ts` 中定义的计算方法抽到了 `src/utils.ts` 中，在 `index.ts` 中只负责处理 `LaunchApp` 的相关逻辑
- 根据改动更新了 readme

**Further changes:**
- 下一步可以更进一步改进 Readme，使得文档更易读。

2021-02-20 06:17 UTC, hanpanpan200 commented
@jawidx 感谢你开源的这个 repo，它在我的项目中起到了非常大的帮助，赞！
同时在我的使用和测试过程中发现一点小问题，于是改了一下，提交了几点重构的改动，请帮忙做下review，希望能让这个repo帮助到更多的人！

2021-02-22 12:20 UTC, jawidx requested changes
有几个点感觉不合适，建议修改

2021-02-23 09:41 UTC, hanpanpan200 commented
@jawidx 你好，感谢你的时间！根据comments改了一下~ 麻烦你再帮忙review一下吧！谢谢！

2021-02-23 10:18 UTC, merged

2021-02-23 10:25 UTC, jawidx commented
> @jawidx 你好，感谢你的时间！根据comments改了一下~ 麻烦你再帮忙review一下吧！谢谢！

合了，感谢优化，👍🏻